Add: Full mouse support for rnvimr
kevinhwang91/rnvimr pull request #150
Opened 2023-05-26 15:37 UTC by Zeioth

I hope this makes easier for you to test the feature. Unless you wanna add an option to enable/disable mouse support (which shouldn't really be necessary), that should be all.

2023-05-26 17:38 UTC, kevinhwang91 requested changes

2023-05-26 17:38 UTC, kevinhwang91 commented on autoload/rnvimr.vim
missing `call`

2023-05-26 17:38 UTC, kevinhwang91 commented on autoload/rnvimr.vim
> +        if system('tmux display -p "#{mouse}"')[0]
Should use `TMUX` var
> The update-environment session option may be used to update the session environment from the client when a new session is created or an old reattached.
> tmux also initialises the TMUX variable with some internal information to allow commands to be executed from inside, and the TERM variable with the correct terminal setting of ‘screen’.

2023-05-26 22:59 UTC, Zeioth commented on autoload/rnvimr.vim
Change applied.

2023-05-26 22:59 UTC, Zeioth commented on autoload/rnvimr.vim
> +        if system('tmux display -p "#{mouse}"')[0]
Change applyed

2023-05-27 12:06 UTC, kevinhwang91 commented
Thanks!

2023-05-27 12:07 UTC, merged